In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])
print(x)
print(type(x))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
y=np.array(['1','2',3])
print(y)
print(type(y))

['1' '2' '3']
<class 'numpy.ndarray'>


In [4]:
b=np.linspace(0,20,10,True,True)
b

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

In [5]:
b=np.linspace(0,20,10,False,True)
b

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [6]:
c=np.arange(1,20,1.99)
c

array([ 1.  ,  2.99,  4.98,  6.97,  8.96, 10.95, 12.94, 14.93, 16.92,
       18.91])

In [7]:
c=np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
c=np.ones((3,4),int) #int is for type casting
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
d=np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
e=np.random.rand(3,4)
e

array([[0.51250493, 0.34831131, 0.14466096, 0.33558965],
       [0.2116146 , 0.005329  , 0.66202702, 0.7130347 ],
       [0.45411103, 0.95319314, 0.95522648, 0.82285558]])

In [11]:
f=np.eye(3) #1's for diagonal and 0's for other values
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
x=np.arange(1,10,1)
y=x.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
y.shape

(3, 3)

In [14]:
y=np.arange(11,20,1)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.add(x,y)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
f=np.multiply(x,y)
print(f)
f=np.divide(x,y)
print(f)
f=np.subtract(x,y)
print(f)
f=np.remainder(x,y)
print(f)

[ 11  24  39  56  75  96 119 144 171]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]
[-10 -10 -10 -10 -10 -10 -10 -10 -10]
[1 2 3 4 5 6 7 8 9]


In [19]:
x[1]

2

In [20]:
x[1:5]

array([2, 3, 4, 5])

In [21]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
z[0,0]

1

In [23]:
z[1,0]

4

In [24]:
z[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [25]:
y=x.copy()
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
p=x

In [27]:
p

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
p[0]=100
p

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [29]:
x


array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
x=np.append(x,[10,11,12],axis=0)
x

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [31]:
x=np.append(x,[10,11,12],axis=0)
x

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  10,
        11,  12])

In [32]:
x=np.matrix("1,2,3;4,5,6;7,8,9")
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
a=np.arange(0,20,1)
b=a.reshape(5,4)
c=np.matrix(b)
c

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [34]:
type(c)

numpy.matrix

In [35]:
d=np.matrix(np.arange(0,20).reshape(5,4))

In [36]:
d

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [37]:
e=np.matrix(np.arange(10,30).reshape(5,4))
e=np.transpose(e)
e

matrix([[10, 14, 18, 22, 26],
        [11, 15, 19, 23, 27],
        [12, 16, 20, 24, 28],
        [13, 17, 21, 25, 29]])

In [38]:
f=np.dot(c,e)

In [39]:
f

matrix([[  74,   98,  122,  146,  170],
        [ 258,  346,  434,  522,  610],
        [ 442,  594,  746,  898, 1050],
        [ 626,  842, 1058, 1274, 1490],
        [ 810, 1090, 1370, 1650, 1930]])

In [40]:
g=np.linalg.det(f)
g

0.0

In [46]:
h=np.linalg.inv(f)
h

LinAlgError: Singular matrix

In [47]:
q=np.matrix(np.arange(0,25).reshape(5,5))
q=np.linalg.inv(q)
q

LinAlgError: Singular matrix